# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install coveralls
- python setup.py install

before_install:
- pip install coverage
- sudo apt-get install -qq python-numpy
- pip install tensorflow

script:
- coverage run --source=Schrodinger setup.py test
- coverage report -m

after_success: coveralls
language: python

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wfunkenbusch
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: wfunkenbusch/Schrodinger
    python: 3.6
